---
- name: Check if Alloy is installed
  ansible.builtin.stat:
    path: /usr/bin/alloy
  register: alloy_stat
  changed_when: false

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gpg
      - curl
    state: present
    update_cache: true
  when: not alloy_stat.stat.exists

- name: Download Grafana GPG key
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /tmp/grafana.asc
    mode: "0644"
  when: not alloy_stat.stat.exists

- name: Convert Grafana GPG key to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/grafana.gpg /tmp/grafana.asc
    creates: /usr/share/keyrings/grafana.gpg
  when: not alloy_stat.stat.exists

- name: Add Grafana apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main"
    state: present
    filename: grafana
  when: not alloy_stat.stat.exists

- name: Install Grafana Alloy
  ansible.builtin.apt:
    name: alloy
    state: present
    update_cache: true
  when: not alloy_stat.stat.exists

- name: Enable and start Alloy service
  ansible.builtin.systemd:
    name: alloy
    enabled: true
    state: started
  changed_when: false
