- name: Verificar si xtop ya está instalado
  ansible.builtin.command: xtop --version
  register: xtop_installed_version
  changed_when: false
  failed_when: false
  tags: install_xtop

- name: Descargar e instalar xtop
  ansible.builtin.apt:
    deb: "https://github.com/ftahirops/xtop/releases/download/v{{ xtop_version }}/xtop_{{ xtop_version }}-{{ xtop_deb_release }}_amd64.deb"
    state: present
  when: xtop_installed_version.rc != 0 or xtop_installed_version.stdout != xtop_version
  tags: install_xtop
- name: Verificar la instalación de xtop
  ansible.builtin.command: xtop --version
  register: xtop_installed_version_check
  tags: install_xtop
- name: Mostrar la versión de xtop instalada
  ansible.builtin.debug:
    msg: "La versión de xtop instalada es: {{ xtop_installed_version_check.stdout }}"
  tags: install_xtop
  