---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  register: system_update_result
  tags:
    - update

- name: Upgrade packages safely
  ansible.builtin.apt:
    upgrade: safe
    autoremove: true
    autoclean: true
  register: system_update_upgrade_result
  notify:
    - Show updated packages
  tags:
    - upgrade
