- name: Update cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  register: update_result
  tags:
    - update
    - system_update
- name: Upgrade packages
  apt:
    upgrade: safe
    autoremove: true
    autoclean: true
  register: upgrade_result
  notify:
    - Mostrar paquetes actualizados
  tags:
    - upgrade
    - system_update

