---
- name: Create destination directory for custom scripts deployment
  ansible.builtin.file:
    path: "{{ copy_files_dest }}"
    state: directory
    mode: "0755"
  tags: copy_files

- name: Deploy files to target hosts
  ansible.builtin.copy:
    src: "files/{{ item.src }}"
    dest: "{{ copy_files_dest }}/{{ item.src }}"
    mode: "{{ item.mode }}"
  loop: "{{ copy_files_list }}"
  tags: copy_files
