galaxy_info:
  role_name: packages
  description: Install essential system packages
  author: jairdavish
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - packages
    - apt
    - system

dependencies: []
allow_duplicates: false
